update demo script and policies
Signed-off-by: Jim Bugwadia <jim@nirmata.com>

diff --git a/unsigned-pipeline/build/task-build-push-image.yaml b/unsigned-pipeline/build/task-build-push-image.yaml
--- a/unsigned-pipeline/build/task-build-push-image.yaml
+++ b/unsigned-pipeline/build/task-build-push-image.yaml
@@ -2,7 +2,8 @@ apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
   annotations:
-    cosign.sigstore.dev/imageRef: ghcr.io/tap8stry/kaniko:v1
+    cosign.sigstore.dev/message: H4sIAAAAAAAA/wBKBrX5H4sIAAAAAAAA/+xXbVPcOBLO5/kVfV6qAlX4bRhmwFfcLQssRSUBCkhuq1IpSiO3bTG25EjyTGaP++9XkjzvwCV7ybfoA8Zyvzzd/XRLo4ka+cOGlalfN6rwWUVyDKakKl99txVFUdTv9exz0N+3z6jr3s3Wfrf3Ku519/YG/bi/t/8q2tuP+71XEH0/CM+vRmkiX0WRKiSrScpJmotJSjbklCZZ9oKdNpj5MxwTGWaiTFGqUPbCYp/XlUwPB0XZ/zPK9B7NCtXrFUY45+FdSEVVS1SK8dzXRPr5n91BtxdFg16/++PCJzX7gFIxwRPQONKCBymOw3E8RE3izojxNIE7okadCjVJiSZJB4BwLjTRTHBlXmFZlRKNuZAMVQIXhk3wm6HXuljNaiwZRxVUjM8hREHcDeJ1WU1ylYClpuNqB6AkQyxb76Sug1EzRMlRowqYCMczg14UdL0OACcVJjAinI1ER9VIjWaKikpWayv56FtbdwVTNmCwnhQo0UiKwLgWQIAKrgnjKB0caEy94FyIvMTXqnUAWogysObeuI1UoOKvNaRYI09BcCBwKugIJaQEK/POU8AvSBuNCpDQAqioKrM7YbpgC4WMlWi+1SVqLKfAODQKpaoJxcDBR06GJSoXgcG3hloZJeRjJgWvkGsFuiAaKDEQkShWTkFIUEgbaVzIZgPvLqiGFkAUEFCa8JTIFN7MawC0bJRGaZJQE0kqWyl/NeOXpELYlpihRE5xB0QGusA2s1o4/C6Prn4X747Pz1pDGWlKnUAQLtJiJVdcXBNdGEvG7FL6nrJ9enXy5uzm94u3Gw42zd4V6AzYzOIXbUqQwnDa1nvZ7snV5d3ZH3erRj1vSeLsj7ub4/vjm/PbVaGcSsNlxym/luIBqQ4dSYRMxnGwH8S/qoJ09/sJ7cf9/iAeZIMMo+EgJb3eYXRADw/68d4AaYZk2I2zvRjp3uFhN+tj3D3IsuyAHPaGeED2nw7SlUJwmBSMFrOWmLCytKTYbrECU+Dg7CzF9dv7i7enZzf3s6pJVE2pn2LCKctR6dX6PzRKW4d6gwH+6cX52e3dpp2TgjCuTFEyljfSTijIxKxZU+tm3dr9X7T2/ubthqn3N28BOgBKY90GSmTejikftrZdMwSLku+0n3w/nfPzaC63IOVCrqXc0db2RMiR7XsVuCkV1EQXO+FcveXekg9UmnEbycKJhb6QEZT5JZmKRvvG3Lf4Cd2MXsoz8vEs+OU2uz+5uvz94tx+ARiTssEEWqaHgcuE6ztrMYG8cM2gSX2gtJyut8FSJdxthnB3o7Ef7CRjenriUpe0fmXDj9V7hTKByG6NRdlU+E40XM9rVpk3M0eeAThzKzFnBpmvkEp00ZvEMZ6fMpnAs2ncYIm7hKmjj//2jGkv8dZK5e16elqbD1bS2/UaWT4p5irhJZ636101um60PZJPmbTif62w3n8+zZBqlFXLp3eoFMnx2lHmJX10l4H2fJtFHY6ET+raSbaCX2ohNcoXifCEfDKOgrgfdJdIMZFMrxDzaynx9SV8DuDD5yUcDoGvhd9OQwfGDp0EHlsUlGj4XzmER3j4DK+Dj9GnwDbQa/DlAzyCRoTQ3Z7C1km4NjZ/nI/7FR9ICwFrrIR/PKM5m6dfn3GXUioUy7lv/7Aqf5EsTjaJg0HLDit43ZTltSgZnSZwXE7IVK0QFD564ZDxUBXeLng+9T59E86lIQjwC5jLJ8um5lq2MgvNGSrxc8MkpuaCQspSTNwwGzFtdlLUSDW44QNUYopcM1Kq1vZLI3YxZN14cjqLqWO0H+eyv/ytDbgz3/q/6cKqfLn/7HXDvh5tbRvji+87cwFW5TeYrZ9Uv26t2XF9DydXtxfnl/fXx7e3/7q6OT3yaqLUJJKpt5A0hPROLAvgA0qWTdsfKd6Wc7YI2AnZP74/wimEqGnLoPYRmO11RYn6AymPtv65CCODj7Dl9sHnCBF8+ru56vC5yAwaSmlu3iznhiBuvM+FMvbMKbV+Ti2AznVXeqWWbEw0mqie1F/myMoJZ0gHq6szA9Ted54/Dd2/M8Tu7dJKm9pvavgvg37e3JMK/moU345oKeBFsy/H7Pq+0/lxv9Z/rp/r5/q5vt/6bwAAAP//oT2lQwAWAAABAAD//8hIo9RKBgAA
+    cosign.sigstore.dev/signature: MEUCIQCGIfnI6qX0GgkQKzgx/cq2aZJhdLJS8DrqZT4mJDMjIAIgfPTB6T4C4K7ZIXJOgV/g6+NGAfqWRUVZpAJxxdq/RZ8=
     tekton.dev/categories: Image Build
     tekton.dev/pipelines.minVersion: 0.12.1
     tekton.dev/tags: image-build
@@ -33,7 +34,7 @@ spec:
   - description: Chains configuration for image digest
     name: IMAGE_DIGEST
   - description: Chains configuration for image URL
-    name: IMAGE_URL  
+    name: IMAGE_URL
   steps:
   - args:
     - $(params.EXTRA_ARGS)
@@ -69,34 +70,35 @@ spec:
       cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee /tekton/results/IMAGE_DIGEST
       echo $(params.IMAGE) > /tekton/results/IMAGE_URL
     workingDir: $(workspaces.source.path)
-  - name: cosign-sign-img
+  - args:
+    - |
+      #!/bin/sh
+
+      cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee img-digest
+      digest=$(cat img-digest)
+      imgRef=$(params.IMAGE)@$digest
+      export COSIGN_PASSWORD="passw0rd"
+      echo "Cosign Verify Image "$imgRef
+      cosign sign --key /etc/cosign/cosign.key $imgRef
+      retVal=$?
+      if [ $retVal -ne 0 ]; then
+        echo "error signing image"
+      fi
+    command:
+    - /bin/sh
+    - -c
+    env:
+    - name: DOCKER_CONFIG
+      value: /secrets
     image: ghcr.io/tap8stry/cosign:1.7.2
     imagePullPolicy: Always
-    command: ["/bin/sh", "-c"]
-    workingDir: $(workspaces.source.path)
-    env:
-      # specifying DOCKER_CONFIG is required to allow buildkit to detect docker credentials
-      - name: DOCKER_CONFIG
-        value: /secrets
-    args:
-      - |
-        #!/bin/sh
-
-        cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee img-digest
-        digest=$(cat img-digest)
-        imgRef=$(params.IMAGE)@$digest
-        export COSIGN_PASSWORD="passw0rd"
-        echo "Cosign Verify Image "$imgRef
-        cosign sign --key /etc/cosign/cosign.key $imgRef
-        retVal=$?
-        if [ $retVal -ne 0 ]; then
-          echo "error signing image"
-        fi
+    name: cosign-sign-img
     volumeMounts:
-      - mountPath: /etc/cosign
-        name: cosign-private-key
-      - mountPath: /secrets
-        name: regcred               
+    - mountPath: /etc/cosign
+      name: cosign-private-key
+    - mountPath: /secrets
+      name: regcred
+    workingDir: $(workspaces.source.path)
   volumes:
   - name: registry-secret
     secret:
@@ -106,7 +108,6 @@ spec:
       secretName: cosign-private-key
   - name: regcred
     secret:
-      secretName: img-registry-secret        
+      secretName: img-registry-secret
   workspaces:
   - name: source
-
diff --git a/unsigned-pipeline/build/task-syft-bom-generation.yaml b/unsigned-pipeline/build/task-syft-bom-generation.yaml
--- a/unsigned-pipeline/build/task-syft-bom-generation.yaml
+++ b/unsigned-pipeline/build/task-syft-bom-generation.yaml
@@ -2,7 +2,8 @@ apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
   annotations:
-    cosign.sigstore.dev/imageRef: ghcr.io/tap8stry/syft-bom-generator:v1
+    cosign.sigstore.dev/message: H4sIAAAAAAAA/wBLBLT7H4sIAAAAAAAA/+xWS2/cthP3eT/F/Dd7iIFQkr1r7z8q0jYPJzDaJEaa5BIEAZcaSexSpEqO7G7qfveCeu172wbJoYB5oTjvGf5mKOJuztwiJTYzBctQo+UkjQ4WvFBHX2dFURSdTyb1Pj0/q/fotDlHUTSZno2PTian4/H0/GR6Eh1F4zO/QfSV/B9clSNuj6LI5VaWPNE8ycxNwrfkHPE0PWCnTabfw2tuw9SoBK0L7STMz3RZ2OThNFfnn6OUxiLN3WSSe+FMh29DYYrSonNSZ4y4Zdnn8Xk0jiZRdPbw26XPS/kerZNGx0A4J6ODBK/D65MZEj8ZzKVOYnjL3XxQIPGEE48HAJoXGMMmbIwduBKFFyi55YXzXwwSdMLKkmofsuAZgsUULWqBA4DOWs1hFtN9SonM0NGWRk/2SimvFMUwjIa13JoVMlmm0EGCsyqDwiQIqbFAOUIpS1RSr4bTkVgtvm7euZS5mSmCX53R245SqbDklAMZcGQs1j68AnBLMuWC3Ionz2CdzgDAoqsU7SqeI06VA5PWpQffuw+gNM7JmUK45qpC4BaZq4RA525TLlVlV7NqLGxb3g659uBDtiiMTTbjrYUGAI6wfItFqThhXAuhvm4+WCt/dXl18fPlq4tPzy6evHtRs6AJNobR/QYpwXq5j9cMPHv99KeLN5+evn71/HJDP3QoLNbl9JG0ReM2c10MzLQf/V0xYHW528Po/o2xc1dygS5wprICA1+K47APbu2Gjnu9ltsDt+HUxxiyXNhAmpB4+X9HdhH6gsbXUXA6DaLVam43UZ2fUVWBL02lqU+l8KcrTrnP22fb1qK7Wiwda/R2KfSFWqpYzITFBKCu2r7AZ9zlq41hpaYa/jWxAVEMt61lhwQM24Pg9IX1dSgqK2nx1GjC3yluDdpKP3bvHNoYoq9Tp3+c942VhKyy6u/TRpEb2JMd3AIhwuh+2+bBsp2Cf5t+1yDCOJlpxom4yFl3M/vyaqTjk2AanC4FryqlroySYhHDY3XDF269mwHugZ/uMl1Ina33JEgHFn+rpAcTGeBKmRuYVVIlc0mekiChIEiMmKMFDzrUJLnqruZQq+9qdgBhioL7x+nDMJxJHbp8+ACGTAw/1uzlCPDGb3tT9/7XSveUGv1dhsoBU3yzWzzHQ7kjh0GTiDA6lRl8v2QIU5OWD8MO5Z0yssjeYPpox1D5cYPWvHfHvabHz/Py0Ze1WY/W4S9PXr+E51cwHDUGN9iXL1/AG0xhOGoi7dkNmqDBXvPIsXo6QGsINjUs0nuuHo1+WCafwgcYNXRgGiGCj9/5R1Ov3FITB1prbOvN49CHPeylUrlnKBwaC3sH6OERujVEOyw1FtqnCIuSFs+kjeGPPwcHhtCarW4EWOw7vzm9av97MmYxk76bWcNoXS8hEK9YbdAw+HY/kXfrbt2t/+T6KwAA//8+cZ3vABAAAAEAAP//nvMz3EsEAAA=
+    cosign.sigstore.dev/signature: MEUCIF96Ft34O4VdZmOF9pjHmTAFpwE7L3p1teG1Gg2iznRUAiEA/9IHWKUQWZjWZDOSJuolLaiCnencXCtFlGqdBb9KJQA=
   name: syft-bom-generator
 spec:
   params:
@@ -40,7 +41,7 @@ spec:
     - mountPath: /steps
       name: steps-volume
     - mountPath: /secrets
-      name: regcred  
+      name: regcred
   - image: ghcr.io/tap8stry/bash
     name: print-sbom
     script: |
@@ -58,40 +59,30 @@ spec:
       echo $(params.sbom-filepath) | tee $(results.sbom-store.path)
     securityContext:
       runAsUser: 0
-  - name: cosign-attach-bom
+  - args:
+    - "#!/bin/sh\n  \n# ls -la /secrets\n# cat /secrets/.dockerconfig > /secrets/coonfig.json\n#
+      cat /secrets/coonfig.json\nimgRef=$(params.image-ref)@$(params.image-digest)\nsbomFp=$(workspaces.source.path)/$(params.sbom-filepath)\necho
+      \"SBOM FP \"$sbomFp\necho \"IMG Ref \"$imgRef\ncosign attach sbom --sbom $sbomFp
+      $imgRef\nretVal=$?\nif [ $retVal -ne 0 ]; then\n  echo \"error attaching SBOM\"\nfi\n"
+    command:
+    - /bin/sh
+    - -c
+    env:
+    - name: DOCKER_CONFIG
+      value: /secrets
     image: ghcr.io/tap8stry/cosign:1.7.2
     imagePullPolicy: Always
-    env:
-      # specifying DOCKER_CONFIG is required to allow buildkit to detect docker credentials
-      - name: DOCKER_CONFIG
-        value: /secrets
-    command: ["/bin/sh", "-c"]
-    args:
-      - |
-        #!/bin/sh
-          
-        # ls -la /secrets
-        # cat /secrets/.dockerconfig > /secrets/coonfig.json
-        # cat /secrets/coonfig.json
-        imgRef=$(params.image-ref)@$(params.image-digest)
-        sbomFp=$(workspaces.source.path)/$(params.sbom-filepath)
-        echo "SBOM FP "$sbomFp
-        echo "IMG Ref "$imgRef
-        cosign attach sbom --sbom $sbomFp $imgRef
-        retVal=$?
-        if [ $retVal -ne 0 ]; then
-          echo "error attaching SBOM"
-        fi
+    name: cosign-attach-bom
     volumeMounts:
-      - mountPath: /steps
-        name: steps-volume
-      - mountPath: /secrets
-        name: regcred       
+    - mountPath: /steps
+      name: steps-volume
+    - mountPath: /secrets
+      name: regcred
   volumes:
   - emptyDir: {}
     name: steps-volume
   - name: regcred
     secret:
-      secretName: img-registry-secret    
+      secretName: img-registry-secret
   workspaces:
   - name: source
