cosign tasks added
Signed-off-by: Shripad Nadgowda <nadgowda@us.ibm.com>

diff --git a/task-build-push-image.yaml b/task-build-push-image.yaml
--- a/task-build-push-image.yaml
+++ b/task-build-push-image.yaml
@@ -69,10 +69,44 @@ spec:
       cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee /tekton/results/IMAGE_DIGEST
       echo $(params.IMAGE) > /tekton/results/IMAGE_URL
     workingDir: $(workspaces.source.path)
+  - name: cosign-sign-img
+    image: icr.io/gitsecure/cosign:1.7.2
+    imagePullPolicy: Always
+    command: ["/bin/sh", "-c"]
+    workingDir: $(workspaces.source.path)
+    env:
+      # specifying DOCKER_CONFIG is required to allow buildkit to detect docker credentials
+      - name: DOCKER_CONFIG
+        value: /secrets
+    args:
+      - |
+        #!/bin/sh
+
+        cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee img-digest
+        digest=$(cat img-digest)
+        imgRef=$(params.IMAGE)@$digest
+        export COSIGN_PASSWORD="passw0rd"
+        echo "Cosign Verify Image "$imgRef
+        cosign sign --key /etc/cosign/cosign.key $imgRef
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+          echo "error signing image"
+        fi
+    volumeMounts:
+      - mountPath: /etc/cosign
+        name: cosign-private-key
+      - mountPath: /secrets
+        name: regcred               
   volumes:
   - name: registry-secret
     secret:
       secretName: img-registry-secret
+  - name: cosign-private-key
+    secret:
+      secretName: cosign-private-key
+  - name: regcred
+    secret:
+      secretName: img-registry-secret        
   workspaces:
   - name: source
 
diff --git a/task-syft-bom-generation.yaml b/task-syft-bom-generation.yaml
--- a/task-syft-bom-generation.yaml
+++ b/task-syft-bom-generation.yaml
@@ -56,8 +56,40 @@ spec:
       echo $(params.sbom-filepath) | tee $(results.sbom-store.path)
     securityContext:
       runAsUser: 0
+  - name: cosign-attach-bom
+    image: icr.io/gitsecure/cosign:1.7.2
+    imagePullPolicy: Always
+    env:
+      # specifying DOCKER_CONFIG is required to allow buildkit to detect docker credentials
+      - name: DOCKER_CONFIG
+        value: /secrets
+    command: ["/bin/sh", "-c"]
+    args:
+      - |
+        #!/bin/sh
+          
+        # ls -la /secrets
+        # cat /secrets/.dockerconfig > /secrets/coonfig.json
+        # cat /secrets/coonfig.json
+        imgRef=$(params.image-ref)@$(params.image-digest)
+        sbomFp=$(workspaces.source.path)/$(params.sbom-filepath)
+        echo "SBOM FP "$sbomFp
+        echo "IMG Ref "$imgRef
+        cosign attach sbom --sbom $sbomFp $imgRef
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+          echo "error attaching SBOM"
+        fi
+    volumeMounts:
+      - mountPath: /steps
+        name: steps-volume
+      - mountPath: /secrets
+        name: regcred       
   volumes:
   - emptyDir: {}
     name: steps-volume
+  - name: regcred
+    secret:
+      secretName: img-registry-secret    
   workspaces:
   - name: source
